### ISSUE TITLE
[esports] 赛程插件的周日判断逻辑有问题

### ISSUE THREAD

**Issue by Jerry-FaGe** [beiyuouo/bbot#11]
emmmm，hello大大我又来了😂

这次是赛程插件的`spiderWanplusLolDateList.py`文件

```python
        # 统计需要追溯的日期所在的周的时间戳
        need_date_list = list()  # 需要抓取的时间戳列表(所有的周日+最早的一天)
        for curr_date_str in all_date_list:
            curr_date = datetime.datetime.strptime(curr_date_str, "%Y%m%d")
            if curr_date.weekday() == 0:  # 若时间戳为周日
                need_date_list.append(curr_date_str)
        need_date_list.append(all_date_list[-1])  # 添加最早的一天
        # print("需要抓取的时间戳总数:", len(need_date_list))
```

关于`if curr_date.weekday() == 0:`这行，`datetime.weekday() == 6`指的才是周日，0为周一

- datetime.isoweekday() 返回的1-7代表周一到周日
- datetime.weekday() 返回的0-6代表周一到周日
- 而标准格式种%w 1-6表示周一到周六，0代表周日

而且这段代码会导致日期为周一（例如"20210301"）时，构造的`need_date_list`==`["20210301", "20210301"]`，传入接口就会返回两组相同的数据。相应的，qq那边也会推送重复信息。

=================================================
另外，我不明白为什么要判断是否周日以及此段代码在esports插件中的作用。按照esports的时间差调用方式，`start_date`和`end_date`只能是同一天，`all_date_list`中也就只能有一个元素，那么这段代码就没有什么意义还会引发bug

我的处理是直接删掉这段代码：

> need_date_list = all_date_list

如果这段代码有具体作用的话请麻烦告知一下谢谢啦🙏

**Comment by yyyanbj** [comment]
emmm 确实有上述问题，下个版本修复一下。这个插件原先是一个区间查询的代码改的，没太自己检查 - -， sry
