### ISSUE TITLE
v2节点

### ISSUE THREAD

**Issue by Yao990x16** [beiyuouo/bbot#12]
请问一下订阅是哪家机场啊?卡卡云?

**Comment by yyyanbj** [comment]
使用的是[V2RayCloudSpider](https://github.com/QIN2DIM/V2RayCloudSpider)提供的API，具体应该有挺多机场的..

**Comment by Yao990x16** [comment]
> 使用的是[V2RayCloudSpider](https://github.com/QIN2DIM/V2RayCloudSpider)提供的API，具体应该有挺多机场的..
用过别的,好多都高延迟TvT,还有就是赛程功能是不是有问题...不是有赛程了吗就是赛程还没出来,我毕设是做赛程订阅和分析app的,将来看能不能添加到我的bot功能上XD

**Comment by yyyanbj** [comment]
有些v2订阅还是延迟挺低的吧233，不行可以试试ssr节点
赛程功能老多问题了orz，最近在忙别的也就没修，话说今天应该没有LPL赛程:laughing:
赛程插件也是基于另一个库的爬虫做的，README里有提到~可以看一下
