### ISSUE TITLE
规范命名

### ISSUE THREAD

**Issue by WCX1024979076** [beiyuouo/bbot#4]
建议规范一下命名，尽量不要用拼音。代码写得挺不错的，值得参考。

**Comment by yyyanbj** [comment]
这个我也考虑过用英文，但是机器人的主要受众还是自己的同学朋友，用拼音大家都懂意思，方便一点哈哈哈哈:laughing:

**Comment by WCX1024979076** [comment]
行吧，这两天我正在做一个qq机器人课表提醒，从你的代码中借鉴了不少，多谢啦，另外祝你新年快乐吧。

**Comment by yyyanbj** [comment]
之前我也有想过做个课表机器人，当时想的是那种能登录教务的，如果有调课也能及时发现，但是不太会Python的异步动态添加apschedule，所以就搁浅了哈哈哈哈，新年快乐~

**Comment by WCX1024979076** [comment]
这个我是做了一个课表的app，然后客户端通过TCP直接上传到python写入数据库中，然后nonebot每分钟去数据库中查一下数据。至于课表这个基本不会变吧，还没想到这个问题，额。

**Comment by yyyanbj** [comment]
哈哈哈反正我们学校挺多老师调课的，每分钟查询感觉会给服务器带来不少压力...

**Comment by WCX1024979076** [comment]
确实哈，等我想办法优化一下吧，刚刚写完，还有一堆bug，额。

**Comment by yyyanbj** [comment]
我看你好像用的不是最新版的代码，应该是我`20210122 v0.1.0 [重要更新]`之前的，emm，那一块可能配置起来有点乱，之后的版本把配置都写在的`.env.dev`中了
不过知道咋用了应该问题也不大:wink:

**Comment by WCX1024979076** [comment]
啊这，能跑起来就行，哈哈哈哈。

**Comment by yyyanbj** [comment]
加油~

**Comment by WCX1024979076** [comment]
嗯，不打扰你了，干就完了，哈哈哈哈。
